name: CI + GitHub Pages CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Python Tests
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest github_tutorial/tests/

  deploy:
    runs-on: ubuntu-latest
    name: Deploy static site to GitHub Pages
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
    steps:
      - uses: actions/checkout@v3

      - name: Upload static site to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: github_tutorial/site/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
